name: Android Build Release Workflow

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Build Project
        run: ./gradlew assemble

      - name: Build Debug APK
        run: bash ./gradlew :app:assembleDebug

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: '1:994326970928:android:2ki953237460aib8a4341c'
          token: '1//0g_0A0dGDawnkCgYIARAAGBASNwF-L9IrLW_wZoOeFw5wN9nSoIqBomPL-Bx1kfoCSz-Tzv3YDo7bXZmCqycMVblvc9yJv18gXqk'
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk

